import { NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { requireRole } from "@/lib/auth";
import { audit } from "@/lib/audit";
import { fromApiError, idSchema } from "@/lib/api";
type Context = { params: Promise<{ id: string }> };
const updateSchema = z.object({ name: z.string().trim().min(1).max(80).optional(), nameTr: z.string().trim().min(1).max(80).optional(), position: z.number().int().min(0).max(100).optional(), isWon: z.boolean().optional(), isLost: z.boolean().optional() });
export async function PATCH(req: Request, ctx: Context) { try { const session = await requireRole("OWNER", "ADMIN"); const id = idSchema.parse((await ctx.params).id); const input = updateSchema.parse(await req.json()); const before = await prisma.pipelineStage.findFirst({ where: { id, tenantId: session.tenantId } }); if (!before) return NextResponse.json({ error: { code: "NOT_FOUND", message: "Stage not found" } }, { status: 404 }); const isWon = input.isWon ?? before.isWon, isLost = input.isLost ?? before.isLost; if (isWon && isLost) return NextResponse.json({ error: { code: "VALIDATION_ERROR", message: "A stage cannot be both won and lost" } }, { status: 400 }); const stage = await prisma.pipelineStage.update({ where: { id }, data: input }); await audit({ tenantId: session.tenantId, actorUserId: session.id, action: "update", entityType: "pipeline_stage", entityId: id, before: { position: before.position }, after: { position: stage.position } }); return NextResponse.json({ stage }); } catch (error) { return fromApiError(error); } }
export async function DELETE(_req: Request, ctx: Context) { try { const session = await requireRole("OWNER", "ADMIN"); const id = idSchema.parse((await ctx.params).id); const stage = await prisma.pipelineStage.findFirst({ where: { id, tenantId: session.tenantId }, include: { _count: { select: { leads: true } } } }); if (!stage) return NextResponse.json({ error: { code: "NOT_FOUND", message: "Stage not found" } }, { status: 404 }); if (stage._count.leads) return NextResponse.json({ error: { code: "STAGE_IN_USE", message: "Move leads before deleting this stage" } }, { status: 409 }); await prisma.pipelineStage.delete({ where: { id } }); await audit({ tenantId: session.tenantId, actorUserId: session.id, action: "delete", entityType: "pipeline_stage", entityId: id }); return NextResponse.json({ ok: true }); } catch (error) { return fromApiError(error); } }
